; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
; default_envs = esp32
default_envs = ATmega328P

[env:ATmega328]
platform = atmelavr
board = ATmega328P
framework = arduino
upload_port = COM19
upload_speed = 115200
monitor_speed = 9600

lib_deps =    
    Servo
    Wire
    MPU6050
    IRremote
    file://lib/LEVEL2_APPLICATIONS/MyCar
    file://lib/LEVEL2_APPLICATIONS/SensorServo
    file://lib/LEVEL3_CONTROL/StateManager

lib_extra_dirs =
    ${PROJECT_DIR}/lib
    C:/Users/34697/Documents/Arduino/libraries

build_flags =
    -D F_CPU=16000000L
    -D ARDUINO_AVR_ATmega328P
    -D ARDUINO_ARCH_AVR
    ; Include paths for new level structure

build_src_filter =
    +<src/*.cpp>
    +<../test/atmega328p/*.cpp>
    +<../lib/*.cpp>

monitor_filters = 
    time
    default

[env:ATmega328P]
platform = atmelavr
board = ATmega328P
framework = arduino
upload_port = COM24
upload_speed = 115200
monitor_speed = 9600

lib_deps =    
    Servo
    Wire
    MPU6050
    IRremote
    file://lib/LEVEL2_APPLICATIONS/MyCar
    file://lib/LEVEL2_APPLICATIONS/SensorServo
    file://lib/LEVEL3_CONTROL/StateManager

lib_extra_dirs =
    ${PROJECT_DIR}/lib
    C:/Users/34697/Documents/Arduino/libraries

build_flags =
    -D F_CPU=16000000L
    -D ARDUINO_AVR_ATmega328P
    -D ARDUINO_ARCH_AVR
    ; Include paths for new level structure

build_src_filter =
    -<src/*.cpp>
    +<../test/atmega328p/*.cpp>
    +<../lib/*.cpp>

monitor_filters = 
    time
    default

;   
[env:esp32]
platform = espressif32
platform_packages = 
    framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32/archive/refs/tags/2.0.14.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_protocol = esptool
upload_port = COM11
monitor_port = COM11
board_build.partitions = huge_app.csv
board_build.flash_mode = qio
board_build.f_cpu = 240000000L
board_build.arduino.memory_type = qio_opi
; upload_flags = 
;     --before=default_reset
;     --after=hard_reset
;     --erase-all

; Configuración de reset y debug
; upload_resetmethod = hard_reset*
debug_tool = esp-builtin
debug_init_break = tbreak setup

build_flags =
    -DCORE_DEBUG_LEVEL=5
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCONFIG_SPIRAM_CACHE_WORKAROUND
    -DCONFIG_SPIRAM_ALLOW_STACK_EXTERNAL_MEMORY

; Configuración de bibliotecas
lib_deps =
    WiFi
    WebServer
    Wire
    SPI
    esp32-camera
    links2004/WebSockets @ ^2.4.1

; Configuración específica para encontrar las bibliotecas locales
build_src_filter =
    -<src/*.cpp>
    +<../test/esp32/*.cpp>
    +<../lib/*.cpp>
    +<../lib/ESP32Server/*.cpp>

lib_extra_dirs = 
    lib
    lib/ESP32Server
