; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:ATmega328]
platform = atmelavr
board = ATmega328P
framework = arduino
upload_port = COM19
upload_speed = 115200
monitor_speed = 9600

lib_deps =    
    Servo
    Wire
    MPU6050
    IRremote

lib_extra_dirs =
    ${PROJECT_DIR}/lib
    C:/Users/34697/Documents/Arduino/libraries

build_flags =
    -D F_CPU=16000000L
    -D ARDUINO_AVR_ATmega328P
    -D ARDUINO_ARCH_AVR
    ; Include paths for new level structure
    -I${PROJECT_DIR}/lib/LEVEL1_Peripherals/Motor
    -I${PROJECT_DIR}/lib/LEVEL1_Peripherals/HCSR04
    -I${PROJECT_DIR}/lib/LEVEL1_Peripherals/LEDRGB
    -I${PROJECT_DIR}/lib/LEVEL1_Peripherals/MPU
    -I${PROJECT_DIR}/lib/LEVEL1_Peripherals/Battery
    -I${PROJECT_DIR}/lib/LEVEL1_Peripherals/SensorServo
    -I${PROJECT_DIR}/lib/LEVEL1_Peripherals/LineTracking
    -I${PROJECT_DIR}/lib/LEVEL1_Peripherals/IrControl
    -I${PROJECT_DIR}/lib/LEVEL2_Application/MyCar
    -I${PROJECT_DIR}/lib/LEVEL3-Control/StateManager
    -I${PROJECT_DIR}/lib/LEVEL0_Definitons
    -I${PROJECT_DIR}/lib/LEVEL1_Peripherals
    -I${PROJECT_DIR}/lib/LEVEL2_Application
    -I${PROJECT_DIR}/lib/LEVEL3-Control

monitor_filters = 
    time
    default
