; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:ATmega328]
platform = atmelavr
board = ATmega328P
framework = arduino
upload_port = COM19
upload_speed = 115200
monitor_speed = 9600

lib_deps =    
    Servo
    Wire
    MPU6050
    IRremote
    file://lib/LEVEL2_APPLICATIONS/MyCar
    file://lib/LEVEL2_APPLICATIONS/SensorServo
    file://lib/LEVEL3_CONTROL/StateManager

lib_extra_dirs =
    ${PROJECT_DIR}/lib
    C:/Users/34697/Documents/Arduino/libraries

build_flags =
    -D F_CPU=16000000L
    -D ARDUINO_AVR_ATmega328P
    -D ARDUINO_ARCH_AVR
    ; Include paths for new level structure

monitor_filters = 
    time
    default

    ; -I${PROJECT_DIR}/lib/LEVEL0_DEFINITIONS
    ; -I${PROJECT_DIR}/lib/LEVEL1_PERIPHERALS
    ; -I${PROJECT_DIR}/lib/LEVEL1_PERIPHERALS/Motor
    ; -I${PROJECT_DIR}/lib/LEVEL1_PERIPHERALS/HCSR04
    ; -I${PROJECT_DIR}/lib/LEVEL1_PERIPHERALS/LEDRGB
    ; -I${PROJECT_DIR}/lib/LEVEL1_PERIPHERALS/MPU
    ; -I${PROJECT_DIR}/lib/LEVEL1_PERIPHERALS/Battery
    ; -I${PROJECT_DIR}/lib/LEVEL2_APPLICATIONS/SensorServo
    ; -I${PROJECT_DIR}/lib/LEVEL1_PERIPHERALS/LineTracking
    ; -I${PROJECT_DIR}/lib/LEVEL1_PERIPHERALS/IrControl
    ; -I${PROJECT_DIR}/lib/LEVEL2_APPLICATIONS
    ; -I${PROJECT_DIR}/lib/LEVEL2_APPLICATIONS/MyCar
    ; -I${PROJECT_DIR}/lib/LEVEL2_APPLICATIONS/SensorServo
    ; -I${PROJECT_DIR}/lib/LEVEL3_CONTROL
    ; -I${PROJECT_DIR}/lib/LEVEL3_CONTROL/StateManager